[package]
name = "cash"
version = "0.1.0"
edition = "2018"
description = "Command line utility for caching and recalling output"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
